name: Build & Push container image to GCR 
on:
  push:
    branches: [ main ]
      
jobs:
  init-build:
    name: Init server, build image, push to GCR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
      with:
        repository: GiladTrachtenberg/Melodify #checks out the source code repo

    - uses: google-github-actions/auth@v1
      with:
         service_account: ${{ secrets.SERVICE_ACCOUNT_NAME }}
         credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY}}

    - name: Configure Docker Client #And Disable all interactive prompts from gcloud cli
      run: |-
        gcloud auth configure-docker --quiet 
    
    - name: Build Container Image
      run: |-
        docker build -t $IMAGE_NAME .

  increment-push:
    name: Increment Tag
    runs-on: ubuntu-latest
    env: 
      IMG_TAG: $ {{ secrets.IMG_TAG }}
      IMAGE_NAME: meldofiy:latest
      PROJECT_ID: gilad-dev-k8s
    steps:
    - name: Increment Tag
      run: |-
        chmod +x ./bumpver.sh 
        echo "GIT_TAG=$(./bumpver.sh $IMG_TAG release)" >> $GITHUB_ENV

    - name: Push Docker Image to GCR
      run: |-
        docker tag $IMAGE_NAME gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        
    - name: Bump Build version
      env:
        token : ${{ secrets.GH_PAT }}
        GIT_TAG : ${{ env.GIT_TAG }}
      run: |
        echo $token > token.txt
        gh auth login --with-token < token.txt
        gh secret set IMG_TAG -b $GIT_TAG
        echo Bumped Version to : $GIT_TAG


      
